### ISSUE TITLE
ClipOverlappingAlignment doesn't clip one base starting from 3'-end

### ISSUE THREAD

**Issue by milnikol** [BimberLab/DISCVRSeq#123]
When a read needs to be soft-clipped from the 3'-end only by one base, the `ClipOverlappingAlignment` leaves the read as is (no clipping is performed). If the read is shifted to the right for one position, the `ClipOverlappingAlignment` performs the clipping as expected, as it soft-clips two bases (see example below, extensions changed as .bed and .sam not supported by github).
Tool version is 1.27.

[intervals.csv](https://github.com/BimberLab/DISCVRSeq/files/6676923/intervals.csv) 
[testSAM.txt](https://github.com/BimberLab/DISCVRSeq/files/6676930/testSAM.txt)
[soft_clipped_SAM.txt](https://github.com/BimberLab/DISCVRSeq/files/6676932/soft_clipped_SAM.txt)

**Comment by bbimber** [comment]
@milnikol Thanks for the report. I will look into this.

**Comment by bbimber** [comment]
Thanks for the helpful test case. In this instance I think this is what's happening:

- Bed files are 0-based, so the interval 249-1000 is actually base pairs 250 to 1000
- Your first alignment starts at bp 100, ending on bp 249. Therefore it doesnt actually overlap the BED and isnt clipped
- Your second alignment started at bp 101, ending on bp 250. It overlaps 1 bp. There was a problem in that the tool was over-clipping by 1bp on terminal alignments (it clipped starting at the last base to retain). This resulting in your second alignment getting a 2bp softclip, not 1. 

I pushed this bugfix to release 1.3.1: https://github.com/BimberLab/DISCVRSeq/releases/tag/1.3.1

**Comment by milnikol** [comment]
@bbimber Thank you so much for the prompt answer and fix!
