### ISSUE TITLE
ClipOverlappingAlignments does not clip a read if a read fully overlaps a region

### ISSUE THREAD

**Issue by milnikol** [BimberLab/DISCVRSeq#124]
When a read fully overlaps a region (region is smaller than the read), the tool performs no clipping of the read, just leaves it as it is. It does require basically to create two new reads, one that ends at the region begin and the other that starts at the region end, but would this be possible in the future? The tool version is 1.27.

[intervals.txt](https://github.com/BimberLab/DISCVRSeq/files/6677392/intervals.txt)
[testSAM.txt](https://github.com/BimberLab/DISCVRSeq/files/6677418/testSAM.txt)
[soft_clipped_SAM.txt](https://github.com/BimberLab/DISCVRSeq/files/6677420/soft_clipped_SAM.txt)

**Comment by bbimber** [comment]
@milnikol This is actually the point of the tool. We wrote it primarily to deal with removing partial primer sequence from SARS-CoV-2 sequencing. Could bedtools handle this type of request?

**Comment by milnikol** [comment]
@bbimber Oh ok, I understand. Bedtools intersect does not clip the reads, it just looks for an overlap between reads and regions. I would need the reads to be clipped. Thank you!

**Comment by bbimber** [comment]
what about bedtools subtract? i dont know how it handles BAMs, but in principle that's the kind of operation you want, right?

https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html

**Comment by milnikol** [comment]
Same thing as bedtools intersect, it does not clip the reads but only cares if there is an overlap.. Btw, even though it is not stated in the documentation, BAM can be an input via `-abam` parameter. Thanks anyway!
