### ISSUE TITLE
VariantQC with more than one vcf ?  

### ISSUE THREAD

**Issue by quentin67100** [BimberLab/DISCVRSeq#140]
Hello, 

I try to run VariantQC with singularity. But i obtained this error when i try to run more than one vcf. It's not possible to obtained one report for multiple vcf ? 
I precise that if i run each vcf independently it's work. 

```
UNEXPECTED ERROR: null

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
java.lang.NullPointerException
        at com.github.discvrseq.walkers.variantqc.VariantQC.initializeReports(VariantQC.java:216)
        at com.github.discvrseq.walkers.variantqc.VariantQC.onTraversalStart(VariantQC.java:335)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1061)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at com.github.discvrseq.Main.main(Main.java:50)
```

**Comment by bbimber** [comment]
Helo,

Thanks for reporting the issue. I dont think this has anything to do with singularity. As you note, the tool currently is expecting to run against a single input VCF. I agree it should make a lot more clearly than this.

I will take a look and see if there's a good reason why we dont support multiple input VCFs.

**Comment by quentin67100** [comment]
Thank you for your really fast reply. 
So the only way to produce a report with more than one sample is to use a multi sample vcf ?
As it's possible to write result as a json, there is by chance, any simple solution to run variantQC for each vcf and then merge all the report in only one report ? As multiQC dit for a lot of tools ?

Quentin.

**Comment by bbimber** [comment]
@quentin67100 can you please try version 1.3.4? this is not tested very thoroughly, but in theory it will now support multiple VCFs as input. there were a few somewhat tricky things we had to make sure worked correctly, such as including the VCF's name in the report output. I think this is all working, but we didnt test very thoroughly. We tagged that as a beta feature, but please give it a try and let us know how it works.

**Comment by quentin67100** [comment]
I try the new version with 3 vcf, it produced a report but not a really intersting report because it merge all the vcf, instead of producing a report with information for each input vcf, it produce a report with the total number of variant il all the 3 vcf. And more importantly, for an unknown reason in the report with these 3 vcf the sum is really big ( 170 millions of variants while in a classical vcf there are arround 4 to 5 millions).
And also it not running in parrallel so it could be really long for big dataset.
For all these reason maybe the best option should be to create a module for multiQC in order to merge all the individual report ? Because i like your tool and i want to use it

**Comment by bbimber** [comment]
@quentin67100 can you please post the report it created and the exact command you used?

**Comment by quentin67100** [comment]
@bbimber you could download the report here [https://seafile.igbmc.fr/f/1881b984a3e9443898b8/?dl=1](url)

The exact command is : 
```
singularity run ${discvrseq} VariantQC \
-R ${REF_Genome} \
-V ${gVCF_input_DIR}/G632_DA_C001KVP_1_HYH2CDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-V ${gVCF_input_DIR}/G632_DA_C001KVT_1_HYH2CDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-V ${gVCF_input_DIR}/G632_DA_C001KW5_1_HYGHLDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-O ${report_DIR}/${report_html} \
-L ${interval}
```

**Comment by bbimber** [comment]
@quentin67100 Can you please try a command where you name the VCF like this:

```
singularity run ${discvrseq} VariantQC \
-R ${REF_Genome} \
-V:vcf1 ${gVCF_input_DIR}/G632_DA_C001KVP_1_HYH2CDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-V:vcf2 ${gVCF_input_DIR}/G632_DA_C001KVT_1_HYH2CDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-V:vcf3 ${gVCF_input_DIR}/G632_DA_C001KW5_1_HYGHLDSXX.DUAL2.trimmed.align.filtered.dedup.fixed.recal.g.vcf.gz \
-O ${report_DIR}/${report_html} \
-L ${interval}
```

This name should be reported in the report. I wonder if lacking the name is lumping them together.

Second, what's the value for ${interval}? I think the order of this might dictate the output's order.

**Comment by quentin67100** [comment]
@bbimber The interval is a picard style interval with a natural order 

![image](https://user-images.githubusercontent.com/51077979/132822515-9ff7bc81-b0d2-433d-bc0c-7593a68fae6f.png)

**Comment by quentin67100** [comment]
@bbimber I try the new command and it's work (except for the order of contig). 
But the only issue is the running time because with only one command it's not possible to parrallelize and for a big dataset the running time will be prohibitively long (for only 3 vcf it took 4 hours).

**Comment by bbimber** [comment]
@quentin67100 I see why the suboptimal sorting is happening. We run VariantEval under the hood, and this tool is outputting rows in this order. I have some ideas on how to improve this, but it'll take a little more time. 

I did however, add support for multi-threading (see --threads). This is quite untested and I'm not sure how much it speeds up in practice, but please give this a try. I updated version 1.3.4 in-place.
