### ISSUE TITLE
Using VariantQC with csi index

### ISSUE THREAD

**Issue by jd3234** [BimberLab/DISCVRSeq#236]
Hi BimberLab,

I am trying to use VariantQC on a VCF based on a wheat genome. Wheat genomes are huge and a tbi index can't handle these instead a csi index is needed. Could you add support for csi indices? 
I tried using gatk IndexFeatureFile for indexing but it also does not seem to support large genomes.

Thanks!
Janina

**Comment by bbimber** [comment]
@jd3234: our VCF reading is purely based on the standard java libraries, also used in GATK (which is HTSJDK). What specific error do you see?

I googled GATK/CSI support and it seems maybe it's only implemented for BAMs but not VCFs in HTSJDK? This post is a little old though:

https://github.com/broadinstitute/gatk/issues/6110

you could consider asking the HTSJDK community whether VCF/CSI indexes are on their roadmap: https://github.com/samtools/htsjdk/issues
