### ISSUE TITLE
MergeVcfsAndGenotypes option --setKey not working

### ISSUE THREAD

**Issue by wcarre** [BimberLab/DISCVRSeq#244]
Hi,

I am trying to use the setKey option the same way I used in in GATK 3. But nothing added to the INFO field in the VCF.
The merging of the variant is done but not the info where it comes from.

java  -jar /ngs/programs/DISCVRSeq/DISCVRSeq-1.3.13.jar MergeVcfsAndGenotypes -R {params.genome} -V:HC {input.HC} -V:FB {input.FB} -V:VD {input.VD} -V:MA {input.MA} -O {output.vcf} -genotypeMergeOption UNSORTED --setKey CALLER

Thanks for your help

**Comment by bbimber** [comment]
@wcarre: the was asked here: https://github.com/BimberLab/DISCVRSeq/issues/189. Can you look at this and comment?
