### ISSUE TITLE
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/VariantTransformer.

### ISSUE THREAD

**Issue by justin-mbca** [BimberLab/DISCVRSeq#51]
Hello Everyone,

I encountered the following error when I ran VariantQC using the sample input file. 
Does anyone know how to resolve this issue?

Thanks,

Justin

**java -jar DISCVRSeq-1.07.jar VariantQC -R human_g1k_v37.fasta -V SimpleExample.vcf.gz -O output.html**

12:05:59.713 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/justinzhang/app/DISCVRSeq-1.07/DISCVRSeq-1.07.jar!/com/intel/gkl/native/libgkl_compression.dylib
12:06:01.439 INFO  VariantQC - ------------------------------------------------------------
12:06:01.440 INFO  VariantQC - DISCVR-seq Toolkit v1.07
12:06:01.440 INFO  VariantQC - For support and documentation go to https://software.broadinstitute.org/gatk/
12:06:01.441 INFO  VariantQC - Executing as justinzhang@Xianglis-MacBook-Pro.local on Mac OS X v10.13.6 x86_64
12:06:01.441 INFO  VariantQC - Java runtime: Java HotSpot(TM) 64-Bit Server VM v13+33
12:06:01.442 INFO  VariantQC - Start Date/Time: October 10, 2019 at 12:05:59 PM EDT
12:06:01.442 INFO  VariantQC - ------------------------------------------------------------
12:06:01.442 INFO  VariantQC - ------------------------------------------------------------
12:06:01.443 INFO  VariantQC - HTSJDK Version: 2.18.0
12:06:01.443 INFO  VariantQC - Picard Version: unknown
12:06:01.443 INFO  VariantQC - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:06:01.444 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:06:01.444 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:06:01.444 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:06:01.444 INFO  VariantQC - Deflater: IntelDeflater
12:06:01.444 INFO  VariantQC - Inflater: IntelInflater
12:06:01.444 INFO  VariantQC - GCS max retries/reopens: 20
12:06:01.444 INFO  VariantQC - Requester pays: disabled
12:06:01.445 INFO  VariantQC - Initializing engine
12:06:01.637 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/justinzhang/daiichi/SimpleExample.vcf.gz
12:06:01.731 INFO  VariantQC - Done initializing engine
12:06:01.743 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
log4j:WARN No appenders could be found for logger (org.reflections.Reflections).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
12:06:02.203 INFO  VariantEvalChild - Creating 3 combinatorial stratification states
12:06:02.228 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
12:06:02.232 INFO  VariantEvalChild - Creating 123 combinatorial stratification states
12:06:02.267 INFO  VariantEvalChild - Creating 33 combinatorial stratification states
12:06:02.290 INFO  VariantEvalChild - Creating 264 combinatorial stratification states
12:06:02.319 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
12:06:02.324 INFO  VariantEvalChild - Creating 1353 combinatorial stratification states
12:06:02.350 INFO  VariantQC - Reference has too many contigs, subsetting to the first 40
12:06:02.353 INFO  VariantEvalChild - Creating 984 combinatorial stratification states
12:06:02.397 INFO  VariantEvalChild - Creating 24 combinatorial stratification states
12:06:02.421 INFO  VariantEvalChild - Creating 24 combinatorial stratification states
12:06:02.421 INFO  ProgressMeter - Starting traversal
12:06:02.421 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
12:06:02.424 INFO  VariantQC - Shutting down engine
[October 10, 2019 at 12:06:02 PM EDT] com.github.discvrseq.walkers.variantqc.VariantQC done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=163577856
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/VariantTransformer. Method 'htsjdk.variant.variantcontext.VariantContext lambda$identity$76d6cab0$1(htsjdk.variant.variantcontext.VariantContext)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
at org.broadinstitute.hellbender.transformers.VariantTransformer.identity(VariantTransformer.java:32)
at org.broadinstitute.hellbender.engine.VariantWalkerBase.makePreVariantFilterTransformer(VariantWalkerBase.java:129)
at org.broadinstitute.hellbender.engine.VariantWalkerBase.getTransformedVariantStream(VariantWalkerBase.java:153)
at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:103)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
at com.github.discvrseq.Main.main(Main.java:50)

**Comment by bbimber** [comment]
Hello,

I believe you're hitting a version of this error:

https://gatkforums.broadinstitute.org/gatk/discussion/10888/java-lang-incompatibleclasschangeerror-gatk-4

Can you confirm what version of java you are using?

**Comment by justin-mbca** [comment]
Thanks,

I use Java version  Java SE 13

It works after changing to "Java SE 8"

**Comment by bbimber** [comment]
OK, glad it works.  We'll update the docs to reflect java versions.

Also - I just pushed an update the might be a substantial performance improvement on VariantQC.  You might want to download 1.08.
