### ISSUE TITLE
VariantQC API for generating csv files for Variant Summary 

### ISSUE THREAD

**Issue by justin-mbca** [BimberLab/DISCVRSeq#53]
Hello,

Would it be possible to generate csv files for "Variant Summary" displayed in Html report? Any API? I like to have csv files in my pipeline. 

Thanks,

Justin

**Comment by bbimber** [comment]
Hello,

There is a --rawData argument that will output the raw data as JSON.  we use this internally to aggregate and parse these data - would this work?

https://bimberlab.github.io/DISCVRSeq/toolDoc/com_github_discvrseq_walkers_variantqc_VariantQC.html#--rawData

**Comment by justin-mbca** [comment]
Thanks for the response! It works.
