### ISSUE TITLE
Multithreaded option for VariantQC

### ISSUE THREAD

**Issue by jhchung** [BimberLab/DISCVRSeq#56]
Hello,

This is a very interesting tool that I would like to try out. I'm wondering if there is a multithreaded option for VariantQC or if there is a recommended way of performing QC for whole genome sequencing data on ~2000 individuals. 

* Split by individual?
* Split by chromosome? or smaller genomic regions?
* How to combine results from various runs?

Thanks,
-Jon

**Comment by bbimber** [comment]
Hi Jon,

Thanks for your interest.  At the moment, unfortunately there is no parallelization option.  Under the hood it uses GATK4 VariantEval, which also lacks this.  We have been running VariantQC on similar sized data.  You could however consider splitting into jobs per chromosome/contig.  You might have seen the argument to export rawData as JSON?  If you divide the jobs, you could consider parsing that and aggregating it (i recognize that's not ideal).  We've talked about ways to speed it, such as trying to shift to a Spark tool, but unfortunately havent had the time to explore that.

-Ben

**Comment by jhchung** [comment]
Hi Ben,

Thanks for the info. 

Thanks for pointing out the JSON export feature. Is there any documentation on how to use that file and generating an html report from it?

**Comment by bbimber** [comment]
Hi Jon,

Unfortunately, current there really isnt.  This is meant as an advanced feature for informaticians.  We have used it a little for the purpose of parsing results across VCFs and in certain cases making hard thresholds for warnings (like listed any sample with high private SNPs).

The structure of the JSON basically follows the report HTML.  there are sections, and within each section there's an object per report.  The report has a data array, name, label, etc.  

Recreating an new HTML file from modified JSON also isnt the intended use, but it would not be terribly hard.  If you have any familiarity with HTML/JS, you'll see that in an HTML report there is a an object defined that holds the data (this object is literally the same JSON that's written to the file).  One could probably either modify this object, or I might be able to doctor an HTML file for you that reads the JSON in from a separate file.  

I dont know your level of interest and/or skill, but if you were interested and willing to do some work to dig into this I'd be happy to answer questions.

This being said, despite the runtime, we do execute on similarly large VCFs here as our primary mode of getting results.

-Ben

**Comment by dheerajbobbili1988** [comment]
Hi,

Thank you for this tool. On the same note is there an option similar to "--merge-evals" from [here](https://gatk.broadinstitute.org/hc/en-us/articles/360040507171-VariantEval-BETA-#--merge-evals) to merge per chromosome output?

Thanks

**Comment by bbimber** [comment]
Hello - in its current form, VariantQC accepts one VCF as input and therefore doesnt support anything like --merge-evals.  There is some complexity associated with converting to a MultiVariantWalker (what i think would be needed to make this work).  This might not be ideal, but as you probably know you could do a VCF merge upfront, and then run VariantQC.

**Comment by bbimber** [comment]
@jhchung This took much longer than hoped, but we recently significantly reworked how we iterate the VCF which should make it considerably faster, even if not truly multithreaded. please try version 1.26 or higher to get this change.
