### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by rspreafico** [BimberLab/DISCVRSeq#60]
Hi there

just wanted to see whether you would consider maintaining a Docker container? I noticed the last update to the DISCVR-seq container is from a couple of years ago.

Thanks for considering!

Cheers

**Comment by bbimber** [comment]
Hello,

Yes, i'm open to the idea, but which container are you referring to?  There's some unfortunately overlap in names, but another arm of my lab's software develops modules for LabKey server and I think this is what you've found.

What's your use case around docker?

**Comment by rspreafico** [comment]
Thanks so much for being open to the idea!

Yes, I now realize the name overlap. My interest is primarily in VariantQC. Docker would be awesome for ease of integration in pipelines, e.g. Nextflow with AWS Batch backend. 

One option is to develop the Dockerfile internally. Another option is to add DISCVRSeq to bioconda - in that case, bioconda will automatically generate the corresponding biocontainer - killing two pigeons with a stone.

**Comment by bbimber** [comment]
Alright - so a Dockerfile that adds DISCVRseq's JAR into some appropriate container would be pretty simple, and we could easily make that available on Dockerhub.  I'm not especially familiar with bioconda or what value this adds beyond that.  Does the former give you want you're looking for?

**Comment by rspreafico** [comment]
Yes, that would work, thank you!

**Comment by bbimber** [comment]
I didnt try it myself, but I believe each new release will get automatically build on dockerhub:

https://hub.docker.com/repository/docker/bbimber/discvrseq

please let me know if this works for you.

**Comment by rspreafico** [comment]
Works wonderfully! Thanks so much!
