### ISSUE TITLE
A problem about running VariantQC

### ISSUE THREAD

**Issue by groveswallow** [BimberLab/DISCVRSeq#78]
Hi,
I meet a problem about running VariantQC.

code:
java -jar ~/DISCVRSeq-1.19.jar VariantQC -O ./gbm39_vcf_report.html -R ~/ref-vcf-hg38/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -V ./gbm39_hg38_sv.vcf

error log:
***********************************************************************

UNEXPECTED ERROR: Couldn't find state for chr9_KI270718v1_random at node org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode@39fcbef6

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
org.broadinstitute.hellbender.exceptions.GATKException: Couldn't find state for chr9_KI270718v1_random at node org.broadinstitute.hellbender.tools.walkers.varianteval.stratifications.manager.StratNode@39fcbef6

Thank so much!

**Comment by bbimber** [comment]
@groveswallow is there any chance the set of contigs in the VCF and reference FASTA are out of sync?

**Comment by groveswallow** [comment]
emmm,I have checked the file of fa and vcf.The results as follows:

The part head of vcf:
##contig=<ID=chr2_KI270716v1_random,length=153799>
##contig=<ID=chr3_GL000221v1_random,length=155397>
##contig=<ID=chr4_GL000008v2_random,length=209709>
##contig=<ID=chr5_GL000208v1_random,length=92689>
##contig=<ID=chr9_KI270717v1_random,length=40062>
##contig=<ID=chr9_KI270718v1_random,length=38054>
##contig=<ID=chr9_KI270719v1_random,length=176845>
##contig=<ID=chr9_KI270720v1_random,length=39050>
##contig=<ID=chr11_KI270721v1_random,length=100316>

And view the chr9_KI270718v1_random in reference file seem to be also right.

my code:
samtools faidx ref.fasta chr9_KI270718v1_random > chr9_KI270718v1_random.fa

head of chr9_KI270718v1_random.fa:
>chr9_KI270718v1_random
AGGATCCTCTTCCTCATCCACAGATCCAACAGCCGGTAACATTCCGGCCTACAGCACGTC
CCTACCTCAGCTGAACCGCTGGGACCAACACGCCGTACCGCAGCCGCGCACGCCCAGCAC
GCCACTCCCGGCCTGGCCGGGGCCTGACGTCATCACATCGCGACGCTAGCTGATCCCGCC
CGGATTACCTGGGCTCTGGACGAGAACTGCCTCGTCCCTTAGCCACACCCCCCGGGGAGG
TGGGCTCTCCCCGACGACAGCTGGACACGCCCCTGGGCGTGTTCTGTGAACCTGAGCGAC
GCTGCGGAGAGTCCTTAGGGCGCACTAACCACCTGTCTGAAGGTGTCACTGGCGCCTAGA
GCCTTAATAAGCTACTGGCTGTAGGTAGAGCTGAGGCCAGCCTGCTGGAAATCTGGAGTG
GGTAGCCTGACCTAACCAGTTCCCACAGGGCATAGATTTTATCAACTTGATTTTTTAGTC
TCGTTAAAAAAAAAAGTTTTAATTCATAGGGGAAAGAATGGAAGGTTATAACATTACAAT

**Comment by bbimber** [comment]
@groveswallow can you please do a few things to help debug this:

1) can you please post your command and the full output from it?

2) can you run the command with "-L chr9_KI270718v1_random" added? This should in theory limit to that contig. Can you also pick another small contig, perhaps chr9_KI270717v1_random and try this by itself?

Thanks

**Comment by bbimber** [comment]
@groveswallow I'm writing to follow up: did you end up resolving this? if you'd like us to look into it, can you please post the items we asked about above? thanks.

**Comment by groveswallow** [comment]
> @groveswallow I'm writing to follow up: did you end up resolving this? if you'd like us to look into it, can you please post the items we asked about above? thanks.

Really sorry about that.I did not resolve this question.I will try to find the items and post.

**Comment by bbimber** [comment]
@groveswallow OK, that's fine. If there was an easy solution I'd be curious to know (to see if we could make error reporting more informative, for example), but overall glad to hear its working.
