### ISSUE TITLE
 Getting error while running program

### ISSUE THREAD

**Issue by virinea** [BimberLab/DISCVRSeq#86]
Hello! The following problem occurred:

$ java -jar DISCVRSeq-1.22.jar  --list
Error: Invalid or corrupt jarfile DISCVRSeq-1.22.jar

java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)

**Comment by bbimber** [comment]
@virinea Sorry for the issue. Did you try re-downloading the DISCVRseq JAR to be sure this isnt a one-off issue with that download?

**Comment by virinea** [comment]
Java installation  via anaconda3 helped.

**Comment by bbimber** [comment]
OK, glad this worked. Thanks for the interest in DISCVRseq and dont hesitate to post if you have other issues.
